In [1]:
import pandas as pd
import numpy as np

In [2]:
experience = np.array([1, 3, 5, 7, 10])
education = np.array([1, 2, 2, 3, 3])
salary = np.array([35000, 50000, 65000, 85000, 110000])

Beta0 = 20000
Beta1 = 5000
Beta2 = 10000

y_pred = Beta0 + Beta1 * experience + Beta2 * education

print("Predicted salaries:", y_pred)



Predicted salaries: [ 35000  55000  65000  85000 100000]


In [3]:
X = np.column_stack((np.ones(5),experience,education))

Y = salary.reshape(-1, 1)

print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("X:", X)
print("Y:", Y)

X shape: (5, 3)
Y shape: (5, 1)
X: [[ 1.  1.  1.]
 [ 1.  3.  2.]
 [ 1.  5.  2.]
 [ 1.  7.  3.]
 [ 1. 10.  3.]]
Y: [[ 35000]
 [ 50000]
 [ 65000]
 [ 85000]
 [110000]]


In [ ]:
Beta0 = 5000
Beta1 = 2000
Beta2 = 1500

beta = np.array([Beta0, Beta1, Beta2]).reshape(-1, 1)
X = np.array([[exp, edu] for exp, edu in zip(experience, education)])

y_pred = Beta0 + Beta1*experience + Beta2*education
print("predicted salaries:", y_pred)

predicted salaries: [ 8500 14000 18000 23500 29500]
Predected salaries using matrix [[ 8500.]
 [14000.]
 [18000.]
 [23500.]
 [29500.]]


In [8]:
X_values = np.array([1, 2, 3, 4])
Y = np.array([5, 7, 9, 11]).reshape(-1, 1)

X_without_bias = X_values.reshape(-1, 1)
beta_without_bias = np.array([[2]])
prediction_without_bias = X_without_bias @ beta_without_bias

X_with_bias = np.column_stack((np.ones(4),X_values))
beta_with_bias = np.array([[3], [2]])

prediction_with_bias = X_with_bias @ beta_with_bias

print("Prediction without bias:", prediction_without_bias)
print("Prediction with bias:", prediction_with_bias)

Prediction without bias: [[2]
 [4]
 [6]
 [8]]
Prediction with bias: [[ 5.]
 [ 7.]
 [ 9.]
 [11.]]


In [9]:
import numpy as np

X = np.array([
    [1, 2, 1],
    [1, 3, 2],
    [1, 4, 1],
    [1, 5, 2],
    [1, 6, 1],
    [1, 7, 2],
    [1, 8, 1],
    [1, 9, 2],
    [1, 10, 3],
    [1, 11, 3]
])

beta = np.array([
    [5000],
    [2000],
    [1500]
])

Y_pred = X @ beta

print("X shape:", X.shape)
print("Beta shape:", beta.shape)
print("Prediction shape:", Y_pred.shape)

print("\nPredicted Y:")
print(Y_pred)

X shape: (10, 3)
Beta shape: (3, 1)
Prediction shape: (10, 1)

Predicted Y:
[[10500]
 [14000]
 [14500]
 [18000]
 [18500]
 [22000]
 [22500]
 [26000]
 [29500]
 [31500]]
